apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-html
  namespace: {{ .Release.Namespace }}
spec:
  selector: { app: {{ .Release.Name }}-html }
  ports:
  - port: 80
    targetPort: 80
